# Generated by Django 4.2.1 on 2023-05-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
