# Generated by Django 4.2.1 on 2023-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_comment_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='share',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
